### PR TITLE
Feat: use circle ci

### PR DESCRIPTION
**Pull request by dirkmc**
I got the build step working (and verified with [CircleCI local CLI](https://circleci.com/docs/2.0/local-cli/)) but I'm not sure how to verify the deploy step without actually trying it. I guess we just pull the trigger and hope for the best?

### CODE REVIEW

**Comment by magik6k** [comment]
> I guess we just pull the trigger and hope for the best?

:+1:

**Comment by dirkmc** [comment]
@olizilla can you point us to how to set up circleci? (beyond adding the circleci config.yml)

**Comment by magik6k** [comment]
I've enabled it (there is a build on master - https://circleci.com/workflow-run/2774688e-ae43-4de5-8baf-3b6e0895d031)

**Comment by olizilla** [comment]
Looks good to me!

**Comment by olizilla** [comment]
All you can really test with this at the moment is that the pinning to cluster step works. If configure circleci to start building the project before you add the config, then it'll try and build the PR to add the config, and if it works, you get a PR status with the IPFS link on it. The dnslink step hits the dnsimple api, and we don't have a "dry-run" mode just yet.

**Comment by dirkmc** [comment]
I'm getting a timeout trying to load https://igis.io at the moment, is that because of a deploy?

**Comment by olizilla** [comment]
Deploy is fine, it just throws it at cluster, and then updates the dns with the CID it gets back. Unfortunately the problem is super slow discovery of content via the gateway at the moment.

**Comment by dirkmc** [comment]
Got it, thanks @olizilla

**Pull request merged**
