### PR TITLE
Jenkinsfile experiment

### PR DESCRIPTION
**Pull request by magik6k**
- [x] Try to get this working at all
- [x] Turn the scripts into a Makefile

### CODE REVIEW

**Comment by VictorBjelkholm** [comment]
Just noticed that I don't have write access to this repository and @ImmutableJenkins doesn't either, which will prevent Jenkins from setting the status of the commit here.

**Comment by VictorBjelkholm** [comment]
Also, let me know if something is missing on the workers to get this working.

**Comment by magik6k** [comment]
There are 2 things missing:
* local Ipfs (can be temporary instance), this is easy for me to work around
* Java 8 - There is java 9, though it's quite new and still has a lot of compatibility issues. Downgrading it should be fine as J8 is still supported and most things don't need J9 features yet. I can work around this with docker if there is one

**Comment by magik6k** [comment]
Calling this good-enough for now

**Pull request merged**
