### PR TITLE
Setup CI

### PR DESCRIPTION
**Pull request by magik6k**

### CODE REVIEW

**Comment by dirkmc** [comment]
I think this should fix the styles issue: https://github.com/ipfs-shipyard/IGiS/pull/15

**Comment by dirkmc** [comment]
@magik6k are you sure it needs the # router? Seems to work ok without it

**Comment by magik6k** [comment]
> @magik6k are you sure it needs the # router? Seems to work ok without it

It does, but it results in links like https://ipfs.io/repo/z8mWaFhNutrvGaKNcybtLjgLMEC3n5tC5 which don't work. What we'd need is some way to setup routing on ipfs side (there are some proposals such as 404 file and scripted unixfs)

**Comment by dirkmc** [comment]
Ah I see what you mean, I'll take a look

**Comment by magik6k** [comment]
Merging as it does what it sohuld do

**Pull request merged**
